### ISSUE TITLE
return same value for multiple instances of group

### ISSUE THREAD

**Issue by janhenk** [josh-perry/Tracery.Net#1]
Example:
{
  "origin": "#interjection#, #name#! I'm a #profession#, not a #profession#!",
  "interjection": ["alas", "congratulations", "eureka", "fiddlesticks",
    "good grief", "hallelujah", "oops", "rats", "thanks", "whoa", "yes"],
  "name": ["Jim", "John", "Tom", "Steve", "Kevin", "Gary", "George", "Larry"],
  "profession": ["accountant", "actor", "archeologist", "zoologist"  ]
}

will return values as such:

alas, Tom! I'm a **actor**, not a **actor**!
eureka, Jim! I'm a **actor**, not a **actor**!
oops, Larry! I'm a **archeologist**, not a **archeologist**!
hallelujah, Steve! I'm a **zoologist**, not a **zoologist**!

**Comment by josh-perry** [comment]
Hi!

I don't think is how that's supposed to work according to the [tracery interactive tutorial](http://www.crystalcodepalace.com/traceryTut.html). You can use the symbol save syntax to set properties though which seems to be what you want:

```json
{
	"origin": "#[job:#profession#]sentence#",
	"sentence": "#interjection#, #name#! I'm a #job#, not a #job#!",
	"interjection": ["alas", "congratulations", "eureka", "fiddlesticks",
	"good grief", "hallelujah", "oops", "rats", "thanks", "whoa", "yes"],
	"name": ["Jim", "John", "Tom", "Steve", "Kevin", "Gary", "George", "Larry"],
	"profession": ["accountant", "actor", "archeologist", "zoologist" ]
}
```

gives you:

> good grief, John! I'm a zoologist, not a zoologist!
> fiddlesticks, Gary! I'm a accountant, not a accountant!
> eureka, George! I'm a zoologist, not a zoologist!
> thanks, Gary! I'm a zoologist, not a zoologist!
> good grief, Kevin! I'm a zoologist, not a zoologist!
> rats, Tom! I'm a accountant, not a accountant!
> alas, Kevin! I'm a actor, not a actor!

Check the save [symbol tests](https://github.com/josh-perry/Tracery.Net/blob/master/Tests/SaveSymbolTests.cs) to see how it works.

**Comment by janhenk** [comment]
The problem that it seemed to be work like that as i kept getting the same
profession twice.
After expanding the profession collection it did become random for both.
Perhaps it was a fluke.

Yours truly,

Jan-Henk

Op za 5 mei 2018 19:27 schreef Josh Perry <notifications@github.com>:

**Comment by josh-perry** [comment]
Oh I see, I misread the original comment, my bad.

Closing this ticket, feel free to reopen it if you experience this again.
